const days=[
 {date:'SUN · SEP 13',title:'Your Survival Kit',sub:'Six things packed with love',tpl:'survival',accent:'#e6bd65'},
 {date:'MON · SEP 14',title:'The Focus Game',sub:'A tiny victory between chapters',tpl:'arcade',accent:'#68c9df'},
 {date:'TUE · SEP 15',title:'Gallery of Her Mind',sub:'An exhibition made for Hind',tpl:'museum',accent:'#c68be7'},
 {date:'WED · SEP 16',title:'Study Beside Me',sub:'Five quiet minutes, together',tpl:'cafe',accent:'#6fd6ab'},
 {date:'THU · SEP 17',title:'Build Your Tomorrow',sub:'See where every page leads',tpl:'future',accent:'#f1a46d'},
 {date:'FRI · SEP 18',title:'A Sky Full of Duas',sub:'Light the sky, one prayer at a time',tpl:'sky',accent:'#88aaf0'},
 {date:'SAT · SEP 19',title:'The Final Boss',sub:'Stress never stood a chance',tpl:'battle',accent:'#e56f84'},
 {date:'SUN · SEP 20',title:'The Night She Did It',sub:'A celebration worthy of her',tpl:'finale',accent:'#f0ce76'}
];
const $=s=>document.querySelector(s),opened=new Set(JSON.parse(localStorage.getItem('hind-opened')||'[]'));
const daysEl=$('#days');
days.forEach((d,i)=>{const b=document.createElement('button');b.className='day'+(opened.has(i)?' opened':'');b.style.setProperty('--accent',d.accent);b.innerHTML=`<span class="status">${opened.has(i)?'✓':'✦'}</span><span class="number">0${i+1}</span><h3>${d.title}</h3><p>${d.date} · ${d.sub}</p>`;b.onclick=()=>openDay(i,b);daysEl.appendChild(b)});
function updateProgress(){const n=opened.size,p=Math.round(n/8*100);$('#progressText').textContent=`${n} of 8 opened`;$('#progressPercent').textContent=p+'%';$('#progressBar').style.width=p+'%'}updateProgress();
$('#enter').onclick=()=>{$('#welcome').classList.add('hidden');$('#journey').classList.remove('hidden');window.scrollTo(0,0)};
$('#close').onclick=()=>$('#experience').close();
function openDay(i,b){opened.add(i);localStorage.setItem('hind-opened',JSON.stringify([...opened]));if(b){b.classList.add('opened');b.querySelector('.status').textContent='✓'}updateProgress();const t=document.querySelector(`#${days[i].tpl}`),frag=document.createDocumentFragment();frag.append(t.content.cloneNode(true));frag.append($('#closing').content.cloneNode(true));$('#experienceContent').replaceChildren(frag);$('#experience').showModal();initExperience(days[i].tpl)}
function initExperience(type){
 if(type==='survival')document.querySelectorAll('[data-reveal]').forEach(b=>b.onclick=()=>{b.classList.add('revealed');$('#revealLine').textContent=b.dataset.reveal});
 if(type==='arcade')initGame();
 if(type==='museum')document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>{$('#plaque').innerHTML=`<b>${b.dataset.room}</b><p>${b.dataset.copy}</p>`});
 if(type==='cafe')initFocus();
 if(type==='future')initFuture();
 if(type==='sky')initSky();
 if(type==='battle')initBattle();
 if(type==='finale')initFinale();
}
function initGame(){let score=0,time=20,loop;$('#startGame').onclick=()=>{score=0;$('#score').textContent=0;$('#startGame').remove();spawn();loop=setInterval(()=>{time--;$('#timer').textContent=time;if(time<=0){clearInterval(loop);finish(score>=7?'You did it — exactly as I knew you would.':'Even one step forward is still a victory.') }},1000)};function spawn(){if(score>=7){clearInterval(loop);finish('Seven stars collected. Hind wins again.');return}const s=document.createElement('button');s.className='game-star';s.textContent='✦';s.style.left=8+Math.random()*82+'%';s.style.top=8+Math.random()*75+'%';s.onclick=()=>{score++;$('#score').textContent=score;s.remove();spawn()};$('#gameBoard').appendChild(s)}function finish(msg){$('#gameBoard').innerHTML=`<div style="display:grid;place-items:center;height:100%;text-align:center;padding:2rem;color:#e6bd65;font:600 2rem 'Cormorant Garamond'">${msg}</div>`}}
function initFocus(){let sec=300,loop;$('#focusStart').onclick=()=>{if(loop)return;loop=setInterval(()=>{sec--;$('#focusClock').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;if(sec<=0){clearInterval(loop);$('#focusClock').textContent='You showed up. That matters.'}},1000)}}
function initFuture(){const stages=[['01','Today’s pages','Every page is quietly building something beautiful.'],['02','The exam room','Calm mind. Clear answers. One question at a time.'],['03','Your graduation','The cap, the smile, and everyone proud of the woman you became.'],['04','Your dream career','A future carrying your intelligence, courage, and purpose.'],['05','The life ahead','A beautiful home, answered duas, and someone always cheering for you.']];document.querySelectorAll('[data-stage]').forEach((b,i)=>b.onclick=()=>{document.querySelectorAll('[data-stage]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#futureFill').style.width=i*25+'%';const s=stages[i];$('#futureCard').innerHTML=`<span>${s[0]}</span><h4>${s[1]}</h4><p>${s[2]}</p>`})}
function initSky(){const duas=['Calm','Clarity','Knowledge','Confidence','Strength','Barakah','Success','Joy'];let n=0;$('#duaSky').onclick=e=>{if(n>=duas.length)return;$('#duaPrompt').style.display='none';const s=document.createElement('span');s.className='placed-star';s.textContent='✦';s.style.left=(e.offsetX/e.currentTarget.clientWidth*100)+'%';s.style.top=(e.offsetY/e.currentTarget.clientHeight*100)+'%';s.innerHTML+=`<small>${duas[n++]}</small>`;e.currentTarget.appendChild(s)}}
function initBattle(){let hp=100;document.querySelectorAll('[data-hit]').forEach(b=>b.onclick=()=>{if(hp<=0)return;hp=Math.max(0,hp-Number(b.dataset.hit));$('#health').style.width=hp+'%';$('#battleText').textContent=hp?`Stress weakened. ${hp}% left.`:'Stress defeated. Hind’s courage wins.';if(!hp)document.querySelector('.boss-face').textContent='DEFEATED'})}
function initFinale(){$('.finale').classList.add('open');$('#celebrate').onclick=()=>{const c=$('#confetti');for(let i=0;i<65;i++){const p=document.createElement('i');p.className='piece';p.style.left=Math.random()*100+'%';p.style.background=['#e6bd65','#fff','#c73a65','#65c5d6'][i%4];p.style.animationDelay=Math.random()*.8+'s';c.appendChild(p)}}}
const canvas=$('#stars'),ctx=canvas.getContext('2d');let stars=[];function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;stars=Array.from({length:80},()=>({x:Math.random()*canvas.width,y:Math.random()*canvas.height,r:Math.random()*1.7+.3,a:Math.random()}))}function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);stars.forEach(s=>{s.a+=.015;ctx.globalAlpha=.25+Math.abs(Math.sin(s.a))*.65;ctx.fillStyle='#ffe4a5';ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,7);ctx.fill()});requestAnimationFrame(draw)}addEventListener('resize',resize);resize();draw();
let audioCtx,playing=false;$('#sound').onclick=()=>{if(!audioCtx)audioCtx=new AudioContext();if(!playing){const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=174;g.gain.value=.018;o.connect(g).connect(audioCtx.destination);o.start();$('#sound')._osc=o;$('#sound').textContent='♫';playing=true}else{$('#sound')._osc.stop();$('#sound').textContent='♪';playing=false}};
const route=location.pathname.match(/day-(\d+)/);const queryDay=new URLSearchParams(location.search).get('day');if(route||queryDay){const raw=route?route[1]:queryDay;const i=Math.min(7,Math.max(0,Number(raw)-1));document.body.classList.add('standalone');document.body.dataset.day=`DAY ${i+1} · ${days[i].date}`;openDay(i,null)}
