const ROOT='/hind-exam-lights/';
const days=[
 {date:'Sunday · September 13',kicker:'The first light',title:'Before the world asks anything of you',em:'Remember who you are',lead:'Step into a room built from only one thing: you are already carrying everything you need.',type:'orbs',dua:'May Allah open every difficult door for you, steady your heart, and make the beginning of this week gentle and full of barakah.'},
 {date:'Monday · September 14',kicker:'A moment of stillness',title:'The world can wait',em:'Breathe with me',lead:'For sixty quiet seconds, let the noise fall away. Follow the light. Inhale courage. Exhale pressure.',type:'pulse',dua:'May Allah place calm in your chest, clarity in your thoughts, and strength in every hour of study.'},
 {date:'Tuesday · September 15',kicker:'A private exhibition',title:'The museum of',em:'your extraordinary mind',lead:'Walk through four rooms devoted to the qualities no exam could ever fully measure.',type:'gallery',dua:'May Allah increase you in beneficial knowledge, protect your beautiful mind, and let your effort bloom into success.'},
 {date:'Wednesday · September 16',kicker:'New York ↔ Sana’a',title:'Distance cannot enter',em:'this quiet café',lead:'Rain on the glass. Two seats. One shared silence. Study for five minutes knowing I am beside you in every way I can be.',type:'cafe',dua:'May Allah make the distance easy, surround you with comfort, and reward every sincere effort you make today.'},
 {date:'Thursday · September 17',kicker:'Beyond this week',title:'Every page becomes',em:'part of your future',lead:'Touch each chapter and watch the road ahead illuminate—one beautiful step at a time.',type:'future',dua:'May Allah guide you toward a future more beautiful than you imagine and place goodness in every path you choose.'},
 {date:'Friday · September 18',kicker:'Jumu’ah beneath the stars',title:'A sky filled with',em:'duas for you',lead:'Touch the night and place a star. Each one carries a prayer spoken for you even when we cannot speak.',type:'sky',dua:'May Allah accept every dua made for you, grant you success, protect your heart, and write us a beautiful halal future together.'},
 {date:'Saturday · September 19',kicker:'The final challenge',title:'The storm is loud',em:'but you are stronger',lead:'Use focus, rest, tawakkul, and courage. Watch exam stress lose its power over you.',type:'battle',dua:'May Allah replace your worry with certainty, your tiredness with reward, and every fear with complete trust in Him.'},
 {date:'Sunday · September 20',kicker:'The night she did it',title:'You reached',em:'the other side',lead:'The curtain rises for the woman who kept going. This celebration belongs entirely to you.',type:'award',dua:'May Allah accept all your hard work, grant you results that make you smile, and bless everything waiting beyond these exams.'}
];
const art=i=>`url('${ROOT}assets/day-${i+1}.jpg')`;
function widget(type){
 if(type==='orbs')return `<div class="orb-grid">${[['✦','Clarity','Your mind knows more than fear admits'],['◈','Courage','You have crossed hard days before'],['☾','Tawakkul','Your effort is held by Allah'],['♡','Love','Mine reaches you across every mile']].map(x=>`<button class="orb"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></button>`).join('')}</div>`;
 if(type==='pulse')return `<div class="pulse-wrap"><div><div class="pulse"><div><span id="breath">Breathe in</span><small>FOLLOW THE LIGHT</small></div></div><p class="pulse-note">A private minute of calm, made for you.</p></div></div>`;
 if(type==='gallery')return `<div class="gallery">${[['Discipline','Every hour you choose your future over comfort becomes part of the woman you are becoming.'],['Brilliance','Your intelligence lives in the way you question, learn, adapt, and rise.'],['Courage','Stress may visit, but it never gets to decide how your story ends.'],['Future','One day you will look back and know this was another bridge you crossed beautifully.']].map((x,i)=>`<button class="${i?'':'active'}"><strong>${x[0]}</strong><p>${x[1]}</p></button>`).join('')}</div>`;
 if(type==='cafe')return `<div class="window"><div><div class="seats"><div class="seat"><i>H</i><small>Sana’a</small></div><span class="heart">♡</span><div class="seat"><i>M</i><small>New York</small></div></div><div class="clock" id="clock">05:00</div><button class="action" id="timer">Begin our quiet time</button></div></div>`;
 if(type==='future')return `<div class="timeline">${[['Today’s pages','Every paragraph is quietly building something beautiful.'],['The exam room','You walk in carrying preparation, courage, and every dua made for you.'],['Graduation','A proud smile, a finished chapter, and a new beginning.'],['Your calling','Knowledge becomes the work and impact only you can give.'],['Our tomorrow','A peaceful halal life where we remember the week you refused to give up.']].map((x,i)=>`<button class="chapter ${i?'':'active'}"><b>0${i+1} · ${x[0]}</b><small>${x[1]}</small></button>`).join('')}</div>`;
 if(type==='sky')return `<div class="sky" id="sky"><p class="hint">Touch the darkness to place a dua-star</p></div>`;
 if(type==='battle')return `<div class="battle"><div class="storm" id="storm">EXAM<br>STRESS</div><div class="health"><i id="health"></i></div><div class="powers">${[['Focus',28],['Rest',18],['Tawakkul',32],['Courage',24]].map(x=>`<button data-hit="${x[1]}">${x[0]}</button>`).join('')}</div><small id="battlecopy">The storm looks big. Your strength is bigger.</small></div>`;
 return `<div class="award"><div class="certificate"><span>✦</span><p>The 2026 award for</p><h2>Queen of Never Giving Up</h2><small>Presented to Hind—the woman Musfiqur never stopped believing in.</small></div><button class="action" id="celebrate">Begin the celebration</button></div>`;
}
function render(i){let d=days[i];document.title=`Day ${i+1} · Hind's Week of Light`;document.querySelector('#app').innerHTML=`<section class="scene" style="--image:${art(i)}"><div class="backdrop"></div><div class="grain"></div><header class="top"><div class="brand"><i>H</i>Week of Light</div><div class="counter">Day ${i+1} of 8 · ${d.date}</div></header><div class="panel"><div class="copy"><p class="eyebrow">${d.kicker}</p><h1>${d.title}<em>${d.em}</em></h1><p class="lead">${d.lead}</p></div><div class="experience">${widget(d.type)}</div></div><div class="dua"><b>Today’s dua for you</b><br>${d.dua} Ameen.</div><nav class="nav">${i?`<a aria-label="Previous day" href="${ROOT}?day=${i}">←</a>`:''}${i<7?`<a aria-label="Next day" href="${ROOT}?day=${i+2}">→</a>`:''}</nav></section>`;bind(d.type)}
function bind(type){
 document.querySelectorAll('.orb').forEach(x=>x.onclick=()=>x.classList.add('revealed'));
 document.querySelectorAll('.gallery button').forEach(x=>x.onclick=()=>{document.querySelectorAll('.gallery button').forEach(y=>y.classList.remove('active'));x.classList.add('active')});
 document.querySelectorAll('.chapter').forEach(x=>x.onclick=()=>{document.querySelectorAll('.chapter').forEach(y=>y.classList.remove('active'));x.classList.add('active')});
 if(type==='pulse'){let b=document.querySelector('#breath');setInterval(()=>b.textContent=b.textContent==='Breathe in'?'Breathe out':'Breathe in',4000)}
 if(type==='cafe'){let running=false,left=300,iv;document.querySelector('#timer').onclick=()=>{if(running)return;running=true;iv=setInterval(()=>{left--;document.querySelector('#clock').textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;if(!left){clearInterval(iv);document.querySelector('#timer').textContent='We did it together'}},1000)}}
 if(type==='sky'){let s=document.querySelector('#sky');s.onclick=e=>{let r=s.getBoundingClientRect(),x=document.createElement('span');x.className='star';x.textContent='✦';x.style.left=(e.clientX-r.left)+'px';x.style.top=(e.clientY-r.top)+'px';s.appendChild(x)}}
 if(type==='battle'){let hp=100;document.querySelectorAll('[data-hit]').forEach(x=>x.onclick=()=>{hp=Math.max(0,hp-+x.dataset.hit);document.querySelector('#health').style.width=hp+'%';document.querySelector('#storm').style.transform=`scale(${.65+hp/285})`;if(!hp)document.querySelector('#battlecopy').textContent='The storm is gone. Hind remains.'})}
 if(type==='award')document.querySelector('#celebrate').onclick=()=>{for(let i=0;i<90;i++){let c=document.createElement('i');c.className='confetti';c.style.left=Math.random()*100+'vw';c.style.background=['#f0ce82','#fff','#9cc8ef','#d67b9c'][i%4];c.style.animationDelay=Math.random()*1.2+'s';document.body.appendChild(c);setTimeout(()=>c.remove(),4500)}}
}
let n=Math.min(8,Math.max(1,+(new URLSearchParams(location.search).get('day')||location.pathname.match(/day-(\\d+)/)?.[1]||1)));render(n-1);
